export const COUNTRIES_LIST_REQUEST = "COUNTRIES_LIST_REQUEST",
  COUNTRIES_LIST_ERROR = "COUNTRIES_LIST_ERROR",
  COUNTRIES_LIST_SUCCESS = "COUNTRIES_LIST_SUCCESS",
	SEARCH_COUNTRY = 'SEARCH_COUNTRY',
	
